import type { Metadata } from 'next'
import clsx from 'clsx'
import { inter } from '@/app/ui/fonts'
import Header from "@/app/header";
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, 'p-4')}>
        <Header />
        {children}
      </body>
    </html>
  )
}
